
export const skillSets = [
    "Guidewire BA (PC)",
    "Guidewire BA (BC)",
    "Guidewire BA (CC)",
    "Guidewire QA (PC)",
    "Guidewire QA (BC)",
    "Guidewire QA (CC)",
    "Guidewire Dev (PC)",
    "Guidewire Dev (BC)",
    "Guidewire Dev (CC)",
    "Guidewire Lead (CC)",
    "Business Analyst",
    "Technical Specialist",
    "Guidewire Integration Developer",
    "Guidewire Lead (PC)",
    "Guidewire Lead (BC)",
    "Guidewire Architect",
    "Guidewire QA",
    "Guidewire Portal",
    "Guidewire Datahub",
    "Guidewire Infocentre",
    "Recruitment Executive",
    "Business Development Executive",
    "Guidewire Backend Developer",
    "Duckcreek Developer",
    "Coldfusion Developer",
    "Oneshield Designer",
    "Digital Marketing Executive",
    "Mulesoft Developer",
    "Scrum Master",
    "Project Leader",
    "Oneshield BA",
    "Oneshield QA",
  ];
  